apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml

images:
  - name: goserver
    newName: henriqueholtz/fullcycle-gitops
    newTag: newTag
