FROM golang:1.20

WORKDIR /app

RUN apt-get update && apt-get install -y librdkafka-dev

# tail -f /dev/null stuck the container up and running
# CMD ["tail", "-f", "/dev/null"]
CMD ["go", "run", "cmd/wallet-reflected/main.go"]