name: CD GitOps

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push image to Dockerhub
        users: docker/build-push-action@1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACESS_TOKEN }}
          repository: 'henriqueholtz/fullcycle'
          tags: ${{ github.sha }}, latest
