---
# tasks file for docker_swarm_manager
- name: Init docker swarm
  docker_swarm:
    state: present
  register: init_swarm

- name: Join
  set_fact:
    join_token_worker: '{{ init_swarm.swarm_facts.JoinTokens.Worker }}'
