# - hosts: all
#   become: true # execute as root user after login
#   roles:
# - install_ngnix
# - install_docker

- hosts: manager
  become: true # execute as root user after login
  roles:
    # - install_docker
    - docker_swarm_manager

- hosts: worker
  become: true # execute as root user after login
  roles:
    # - install_docker
    - docker_swarm_worker
