name: '[git-ops] CD'

on: workflow_dispatch

defaults:
  run:
    working-directory: ./fc30/git-ops

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push image to Dockerhub
        uses: docker/build-push-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACESS_TOKEN }}
          repository: 'henriqueholtz/fullcycle'
          tags: ${{ github.sha }}, latest
